export const pedals = [
  {
    id: "1",
    name: "Spacetime",
    manufacturer: "Vahlbruch",
    made_in: "Germany",
    category: ["Delay"],
    mono_stereo: "mono",
    bypass: "true OR buffered",
    voltage: "9V",
    polarity: "center negative",
    input_impedance: "1.0 M Ohm",
    output_impedance: "1.0 k Ohm",
    bypass_current_draw_manufacturer: " mA",
    engaged_current_draw_manufacturer: "60 mA",
    bypass_current_draw_own_measurement: " mA",
    engaged_current_draw_wn_measurement: " mA",
    width_mm: 70,
    depth_mm: 115,
    height_mm: 48,
    imagePath: "/img/Spacetime.png",
    footswitch_1: "on/ off",
    footswitch_2: "",
    footswitch_3: "",
    footswitch_4: "",
    knob_1: "MIX",
    knob_2: "TIME",
    knob_3: "REPEATS",
    knob_4: "",
    knob_5: "",
    knob_6: "",
    knob_7: "",
    knob_8: "",
    switch_1: "bright - mellow - dark",
    switch_2: "",
    switch_3: "",
    switch_4: "",
    switch_5: "",
    switch_6: "",
    switch_7: "",
    switch_8: "",
    internal_dipswitch_1: "TBP/ BBP",
    internal_dipswitch_2: "kill dry",
    power_jack: ["2.1 mm", " TOP"],
    in: "right",
    out: "left",
    exp_in: "",
    sound_description:
      "I like the warm repeats they are just lying behind the signal and give a beatiful ambiendce.",
    my_comment: "AWWWWWSOME DELAY AY AY AY",
    nice_to_know:
      "You can choose if the pedal powers up in on or bypass state. To change the state: Step 1: Unplug the power supply cable. Step 2: Hold down on/off MagTraB button. Step 3: Plug in again the power supply cable. Step 4: Release on/off MagTraB button. DONE! The next time your pedal powers up it will automatically start in the other state.",
    tags: ["#warm", " #slapback", " #alwayson", " #timebased"],
  },
  {
    id: "2",
    name: "DELTA_II",
    manufacturer: "Spaceman",
    category: ["Tremolo", "Harmonic Trem"],
    made_in: "USA",
    mono_stereo: "mono",
    bypass: "true",
    voltage: "9 - 18 V",
    polarity: "center negative",
    input_impedance: "1.0 M Ohm",
    output_impedance: "",
    bypass_current_draw__manufacturer: "19.5 mA",
    engaged_current_draw_manufacturer: "45 mA",
    bypass_current_draw_own_measurement: " mA",
    engaged_current_draw_own_measurement: " mA",
    width_mm: 66,
    depth_mm: 120,
    height_mm: 55,
    imagePath: "/img/Delta_II.png",
    footswitch_1: "on/ off",
    footswitch_2: "",
    footswitch_3: "",
    footswitch_4: "",
    knob_1: "DEPTH",
    knob_2: "FREQ",
    knob_3: "RATE",
    knob_4: "LAG",
    knob_5: "RES",
    knob_6: "",
    knob_7: "",
    knob_8: "",
    switch_1: "VOICE",
    switch_2: "",
    switch_3: "",
    switch_4: "",
    switch_5: "",
    switch_6: "",
    switch_7: "",
    switch_8: "",
    internal_dipswitch_1: "exp_parameter",
    internal_dipswitch_2: "",
    power_jack: ["2.1 mm", " left"],
    in: "right",
    out: "left",
    exp_in: "right",
    sound_description:
      "It is hard to tame the Rate that gets fast quite quickly, but once you tame it, this is classic to fun and back again.",
    my_comment: "Fun of a Trem",
    nice_to_know:
      "ALTERNATE MODES - Apply power with the footswitch depressed. The LAG control transforms into a 4 position mode selector with additional LFO presets. Mode 1 - LFO output 1 runs at normal speed, and LFO output 2 at half speed. Mode 2 - Same as mode 1, but offbeat from each other. Mode 3 - LFO output 2 runs at normal speed, and LFO output 1 at half speed. Mode 4 - Same as mode 3, but offbeat from each other.",
    tags: ["#harmonic", " #versatile", "#expression", "#modulation"],
  },
  {
    id: "3",
    name: "MUDHONEY",
    manufacturer: "T-Rex",
    category: ["Overdrive", "Distortion"],
    made_in: "Denmark",
    mono_stereo: "mono",
    bypass: "true",
    voltage: "8.5 - 12.5 V",
    polarity: "center negative",
    input_impedance: "> 1 M Ohm",
    output_impedance: "< 1 k Ohm",
    bypass_current_draw__manufacturer: "",
    engaged_current_draw_manufacturer: "6 mA",
    bypass_current_draw_own_measurement: " mA",
    engaged_current_draw_own_measurement: " mA",
    width_mm: 100,
    depth_mm: 120,
    height_mm: 55,
    imagePath: "/img/Mudhoney.png",
    footswitch_1: "on/ off",
    footswitch_2: "",
    footswitch_3: "",
    footswitch_4: "",
    knob_1: "GAIN",
    knob_2: "LEVEL",
    knob_3: "TONE",
    knob_4: "",
    knob_5: "",
    knob_6: "",
    knob_7: "",
    knob_8: "",
    switch_1: "BOOST",
    switch_2: "",
    switch_3: "",
    switch_4: "",
    switch_5: "",
    switch_6: "",
    switch_7: "",
    switch_8: "",
    internal_dipswitch_1: "",
    internal_dipswitch_2: "",
    power_jack: ["2.1 mm", " top"],
    in: "top",
    out: "top",
    exp_in: "",
    sound_description:
      "You can cover a lot of tones with this one. Crunch to Fuzz, it is at it is.",
    my_comment:
      "Find a good compromise setting and change drastically by using the boost switch",
    nice_to_know: "",
    tags: ["#crunch", " #fuzzy", " #distortion"],
  },
];
